### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by EdisonJwa** [arnidan/nsfw-api#1]
$ docker run -p 3000:3000 ghcr.io/arnidan/nsfw-api:latest

yarn run v1.22.5
$ node build/index.js
Illegal instruction (core dumped)
error Command failed with exit code 132.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by arnidan** [comment]
What system are you using? What type of processor?

Sorry, my magic ball is broken today

**Comment by EdisonJwa** [comment]
> What system are you using? What type of processor?
> 
> Sorry, my magic ball is broken today

Sorry, I should provide more information about my environment

I'm using archlinux with the docker(`Docker version 20.10.15, build fd82621d35`)
the type of processor is x86-64

let me know if you need more information :)

**Comment by arnidan** [comment]
Just checked it on `Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)`, works well.

Try to build image on your system and see will it work
```bash
git clone https://github.com/arnidan/nsfw-api.git
cd nsfw-api
docker build -t nsfw-api .
docker run -p 3000:3000 nsfw-api
```

**Comment by arnidan** [comment]
Hello, 

I just merged #18. Try to use the updated image. Please, reopen the issue if it won't work

**Comment by EdisonJwa** [comment]
> Just checked it on `Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)`, works well.
> 
> Try to build image on your system and see will it work
> 
> ```shell
> git clone https://github.com/arnidan/nsfw-api.git
> cd nsfw-api
> docker build -t nsfw-api .
> docker run -p 3000:3000 nsfw-api
> ```

Sorry, I was a bit busy that time. But I did run it that time, and it's failed.

Just for sure, I run it again. It does failed


Log File
https://gist.githubusercontent.com/EdisonJwa/5df254df730fdd47194ddacce3e57754/raw/7f560c8acbb1159ef15308e5631e00879d6981b8/gistfile1.txt

> Hello,
> 
> I just merged #18. Try to use the updated image. Please, reopen the issue if it won't work

Still failed

```
 > docker pull ghcr.io/arnidan/nsfw-api:latest                                                 edison@edisonarch 03:31:41
latest: Pulling from arnidan/nsfw-api
ac2fb615420c: Pull complete 
69afbd4475ec: Pull complete 
102a77eae8b4: Pull complete 
6ce783be13c6: Pull complete 
6ae4be244306: Pull complete 
4e4ce58269fd: Pull complete 
fba1f12d0b5b: Pull complete 
33e01f81aa58: Pull complete 
c1b9be1f27ac: Pull complete 
7fb6deeabe85: Pull complete 
b7950c45b428: Pull complete 
Digest: sha256:c4a53c278f1a7d1381bd7a672a7f21e83d0e97f501c5c488e42495d881963ccb
Status: Downloaded newer image for ghcr.io/arnidan/nsfw-api:latest
ghcr.io/arnidan/nsfw-api:latest
~ > docker run -p 3000:3000 ghcr.io/arnidan/nsfw-api:latest                              2m 59s edison@edisonarch 03:34:48
yarn run v1.22.19
$ node build/index.js
Illegal instruction (core dumped)
error Command failed with exit code 132.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by arnidan** [comment]
Oh, I don't understand what's going on. 

Try to build and start it manually without docker like in the [documentation](https://github.com/arnidan/nsfw-api#manual-deploy)

**Comment by jeffscrum** [comment]
I have the same error

```
git clone https://github.com/arnidan/nsfw-api.git
cd nsfw-api
docker build -t nsfw-api .
docker run -p 3000:3000 nsfw-api
```

```
yarn run v1.22.19
$ node build/index.js
Illegal instruction (core dumped)
error Command failed with exit code 132.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Docker version 23.0.3, build 3e7cbfd
Debian 11.6
